// Code generated by mockery v2.49.1. DO NOT EDIT.

package contracts

import (
	context "context"
	entities "go-kafka-chat/intenral/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockChatsRepository is an autogenerated mock type for the ChatsRepository type
type MockChatsRepository struct {
	mock.Mock
}

// AddMessage provides a mock function with given fields: ctx, message, chat
func (_m *MockChatsRepository) AddMessage(ctx context.Context, message *entities.Message, chat *entities.Chat) error {
	ret := _m.Called(ctx, message, chat)

	if len(ret) == 0 {
		panic("no return value specified for AddMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Message, *entities.Chat) error); ok {
		r0 = rf(ctx, message, chat)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: ctx, chat
func (_m *MockChatsRepository) Save(ctx context.Context, chat *entities.Chat) error {
	ret := _m.Called(ctx, chat)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Chat) error); ok {
		r0 = rf(ctx, chat)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockChatsRepository creates a new instance of MockChatsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatsRepository {
	mock := &MockChatsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
